<?php

/**
 * @file
 * Contains httpclientservice.module.
 */

use Drupal\httpclientservice\GenerateContent\Palvelu;
use Drupal\httpclientservice\GenerateContent\Palvelutarjous;
use Drupal\httpclientservice\GenerateContent\Palvelupiste;
use Drupal\httpclientservice\GenerateContent\ClientService;

/**
 * Implements hook_cron().
 */
function httpclientservice_cron() {
  $now = \Drupal::time()->getRequestTime();

  if (httpclientservice_run_cron()) {
    httpclientservice_queue_tasks();
    $this->state->set('httpclientservice.last_cron', $now);
  }
}

/**
 * Check if cron should run.
 */
function httpclientservice_run_cron() {
  $state = \Drupal::state();
  $last_time = $state->get('httpclientservice.last_cron', FALSE);

  if ($last_time < strtotime('-1 days')) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Includes cron tasks.
 */
function httpclientservice_queue_tasks() {
  // Remove All API content.
  // $client = new ClientService();
  // $client->httpclientserviceDeleteEntity('customer_service');
  // $client->httpclientserviceDeleteEntity('service_card');
  // $client->httpclientserviceDeleteEntity('service_offer');

  // Services.
  // $palvelupisteet = new Palvelupiste();
  // $palvelutarjous = new Palvelutarjous();
  // $palvelukortti = new Palvelu();

  // Retrieve all data.
  // $palvelupisteet->httpclientserviceSavePalvelupisteet();
  // $palvelutarjous->httpclientserviceSavePalvelutarjoukset();
  // $palvelukortti->httpclientserviceSavePalvelu();

  // For development purposes retrieve just one item per each.
  // $palvelupisteet->httpclientserviceSavePalvelupisteDev();
  // $palvelutarjous->httpclientserviceSavePalvelutarjousDev();
  // $palvelukortti->httpclientserviceSavePalveluDev();
}
